### PR TITLE
SSO + File upload + Database encryption

### PR DESCRIPTION
**Pull request by Chapizze**
Hello, 

This PR brings couple changes : 

- SSO Integration : Most companies willing to use Pwndoc want to log in with SSO. I added this feature and can be enabled / disabled easily. All is explained inside /docs/sso.md

- File upload : Inside Audit General and Findings tabs, it was missing a way to upload additional useful files such as scripts, .txt .xml .py .sh or any type of file a pentester want to add. 

- Database Encryption : Hosting such sensitive data must be encrypted inside the database. I proposed only the encryption of the Finding and Attachment mongo document

Feel free to reach me out for any question.

Chapizze

### CODE REVIEW

**Comment by MaxNad** [comment]
Hi,

I believe that there are some very useful changes in there. However, bundling them all together makes it very hard to review and test the PR.

If you have a quick way to split the changes, it will be a lot faster for me to merge. Otherwise, it may take more time.

Also, while I understand that you have invested a lot of time in this PR, changing the fundings file is not very respectful for the original owner of the project. I could recommend reverting that if you want the PR to be merged.

Thank you

**Comment by Chapizze** [comment]
Hi, 

Sorry for the fundings, my last commit had been automatically added in the PR. Change it on the way

**Comment by p0dalirius** [comment]
Hi @Chapizze,

I hope you are well,

Your changes are really interesting, such a shame that you decided to drop everything and create a fork instead of contributing here. You stated that your PRs are not reviewed but you closed your one and only PR by yourself here.

Also since you tried to replace the name by yours in the commit https://github.com/pwndoc/pwndoc/commit/79fffc5e4dfec6d4280cc3eaed149450104eb953, I tend to think this was not a mistake but an attempt to take over the sponsorship?

https://github.com/pwndoc/pwndoc/blob/79fffc5e4dfec6d4280cc3eaed149450104eb953/.github/FUNDING.yml#L3

You have created a fork and you have every right to do so. However you changed all the sponsorship in your new repository to your name: https://github.com/AmadeusITGroup/pwndoc1A/blob/e39381ef532b7bb5aae97d9806a18a131bf2f1dc/README.md#L118-L122
And created issues in the two official projects in order to redirect users to your fork, which is a one more layer of disrespect to these projects.

* https://github.com/pwndoc/pwndoc/issues/557
* https://github.com/pwndoc-ng/pwndoc-ng/issues/414

Also since you block anyone objecting with you politely, your actions seems to comfort the idea that this hostile move is intended after all.

There were tons of ways you could have done this better:
- you could have contributed to this project or to pwndoc-ng
- you could have created multiple pull requests instead of one massive PR for lots of features (that is not a best practice), 
- you could have not demanded a sponsorship on your fork (like pwndoc-ng is not asking for a sponsorship)
- you could have not created issues in the original projects to promote your fork

Wishing you all the best nevertheless,

Best regards,

**Comment by Chapizze** [comment]
Hello Remi, 

Let's deep dive into what is happening. 

I first created my fork and then made a pull request. I changed the sponsorship on my fork with has been reflected in the PR. This was not on purpose, as I removed it in my PR, created a new branch on my fork and keep working. 

Then, as my pull request was not reviewed after more than a month, I have decided to open issues to inform users what my features are bringing and that original repositories does not seem active

My code, as all code public in GitHub is opensource and feel free to use it or not. 

My only goal was to propose enhancement, improvement and new key features for the tool. 

But as you can understand, if my work is not taken into account because of the inactivity of the repository, then  I have decided to move forward by my own (As you guys did for pwndoc-ng). 

Now, I haven't asked for any disrespectful comments  and "funny" reactions when I was telling the truth. 

If you don't like my explanations or way of working, then let me go by own.

Cheers,

**Comment by wherka-ama** [comment]
@p0dalirius, @MaxNad : apologies to talk to you via closed PR. I guess you will not even look at that notification. I will try my luck though :smile: 

In short: I represent OSPO for Amadeus - the company @Chapizze works for.

What I see in the comments in this PR really breaks my heart :broken_heart: 

Any chance we can "sit together" and discuss it again?

There were some mistakes made - sure, but it doesn't mean we cannot find a solution here. 

The fork @Chapizze is referring to is created on the AmadeusITGroup as a matter of process. We encourage our employees to create such forks to have an interim environment with the ability to exchange with their team mates. reviewing and testing these things before the PR is created to the upstream, which is always the end goal.
There is absolutely no hostile intention here.

The change in the funding.yml was most likely a genuine mistake. I'm sure we can easily clarify it.


Again, I would really love to have an honest conversation with you guys before we close all the doors shut.  I really hope we can still make this work! Let's try to put our egos aside.

**Comment by MaxNad** [comment]
Hi @wherka-ama,

After pointing out the changed to the fundings file, the pull request was closed by @Chapizze themself and I therefore believed that there were no additional desires to revert the change or proceed with the merge.

Still happy to take the time to review the changes (ideally if submitted in individual PRs because the current codebase seems to have deviated quite a lot and some of the changes like the fundings page and README would not be acceptable for a merge)

**Comment by wherka-ama** [comment]
> Hi @wherka-ama,
> 
> After pointing out the changed to the fundings file, the pull request was closed by @Chapizze themself and I therefore believed that there were no additional desires to revert the change or proceed with the merge.
> 
> Still happy to take the time to review the changes (ideally if submitted in individual PRs because the current codebase seems to have deviated quite a lot and some of the changes like the fundings page and README would not be acceptable for a merge)

Hi @MaxNad ,
thank you very much for your understanding :heart: 

We'll work together with @Chapizze to make this work easier to digest on your side.

Cheers

**Pull request closed without merging**
