### PR TITLE
Adding Parser Count vulnerability by severity

### PR DESCRIPTION
**Pull request by davidlebr1**
This functionality offer the possibility to count the number of vulnerability by severity by adding the function `count`.

Really easy to use:
`{findings | count: 'Critical'}`

### CODE REVIEW

**Comment by tamquanminh** [comment]
great!

**Comment by tamquanminh** [comment]
image

I've been checked and it worked correctly.

Thanks @davidlebr1

**Comment by luisfontes19** [comment]
I needed this but i didn't know it was already implemented... Can you add it to the docs?

**Comment by davidlebr1** [comment]
> 
> 
> I needed this but i didn't know it was already implemented... Can you add it to the docs?

It's actually pending. 

https://github.com/pwndoc/pwndoc/pull/25

**Pull request merged**
