### PR TITLE
added placeholder to add vuln id to report

### PR DESCRIPTION
**Pull request by luisfontes19**
Created a placeholder to add a vuln id in the reports. This id is generated only when creating the report.

placeholder created: {identifier}
example output: RSK-001

the id is a sequencial number prepended with the 3 first chars of the audit report name

### CODE REVIEW

**Comment by yeln4ts** [comment]
Thank you for your involvement :smiley: 

You can check the #24 issue, we talked a little about this. 
I would like the application to be as universal as possible, so I think for vulnerabilities ID the best way is to create a custom category with an additional specific field for this. It won't be automatically generated like yours but users will have the ability to use the specific format they want.

**Comment by luisfontes19** [comment]
Makes sense...

Can we discuss on a way to allow to use ID with the flexibility that you want, while generating them automatically?
Managing this by hand is quite boring...

Also, an issue that I have using categories is that if you actually use them to categorize the vulnerabilities you would need to create the same custom fields in all categories and if you want to change it, change in all as well.

**Comment by nobox910** [comment]
Thanks @luisfontes19,
It worked!

image

**Comment by yeln4ts** [comment]
Yes I understand your point for categories but theoretically they are not supposed to change every day. The only thing is that if you decide to add/update/delete a field after a year of use, you would have to go through all your vulnerabilities under this category to update their fields (trying to think about a way to manage that)

As for the ID, if there is one I think it should be related to the vulnerability so it will be the same reference across different reports. And you'll only need to define it once, boring, but at least it will match your usage perfectly.
Also automatic generation could have unwanted behavior, for example in your request if the report name is **(2020) - Report** it would render **(20-001** which is not very user friendly.

**Comment by luisfontes19** [comment]
you made good points here... This is not the best approach indeed. 

But I'm still trying to see a way of doing it without going through the categories, as I don't find it practical, at least for me...

What do you say if I remove the prepended text, and leave just the id and rename it to index?
This way, you only have an index of the vulnerability in the array, but people could also  use it somehow as an ID.

**Comment by yeln4ts** [comment]
This would solve the naming issue but still leave the issue where the index would be linked to its place in findings. Imagine using the resolution field from #42 and adding or removing findings when reviewing, it could change the order of findings and consequently change their IDs.

So I thought about it and one possibility would be to add an «id» field to the finding model and default it to «IDX-{lastExistingId+1}». This would fix the ID changing issue. If wanting a fix ID across reports you could always create a category with an ID field and use it instead.
As for the text prepending the ID, you could add a filter to change the default «IDX» like this: {identifier | changeID: 'FINDING'} that would resolve to «FINDING-001».

**Comment by luisfontes19** [comment]
@yeln4ts check if that's ok now.

Also I couldn't make the sort of the findings' identifier through mongo, so let me know if there's a better way of doing it.

**Comment by yeln4ts** [comment]
This seems pretty good. Here are some remarks, after that we are good I think 😄 

I don't think this is necessary to use the Max function `Math.max(...row.findings.map(r => r.identifier))` since you are already sorting by identifier, the first item will be the max one

Also the lpad function seems to convert for example **12** to **0012** instead of **012**. And you forgot to apply it in `identifier: "IDX-" + finding.identifier`

Last thing for the documentation could you add the filter in there: https://pwndoc.github.io/pwndoc/#/docxtemplate?id=filters ?

**Comment by noraj** [comment]
Also an additional issue with the actual behavior of adding a custom field to a category is that when you wan to add a value to your custom ID-field you don't know which values are already used.

There are two solution to solve that:

1. #28 add custom columns to the vuln search view so people can add a custom column for their custom fields, eg. here a column for the vuln id. If the column is sortable then you can see at a glance which vuln id are availables or taken.
2. An even better approach wold be to have a kind of auto-completion in the custom field with the already existing values for the field so when you begin to write `IDX-0` you see that ids are taken until `IDX-024` for example.

**Comment by noraj** [comment]
Also I don't feel like the vuld ID should be automatic or auto-incremented. Because you maybe want to have any kind of ID, an external reference or different prefixes (eg. WEB-001, MOB-001, INF-001, etc.). So it should stay a normal input field.

**Comment by luisfontes19** [comment]
@yeln4ts can you check again?

Regarding the sorting, thats the issue that I was telling you about...I'm doing the .sort but for some reason its not working, at least in my setup, so thats why i did that extra line... 
Does it sort properly for you?

**Comment by luisfontes19** [comment]
Sorry for posting here after merging, but I did some changes in my fork regarding this...

Added the prefix as a field to the audit object, this way I can have different prefix per project without changing the template. This is quite common.
Also added the id's in the sidebar so that if you have the same vuln multiple times its easier to differentiate them (I know you only need to have one and add multiple affected scopes but that way you can't have different observations for each and also you can't accurately track the number of vulns)

If you think this is useful let me know and I can put it on a PR
  
image

**Comment by noraj** [comment]
> Added the prefix as a field to the audit object, this way I can have different prefix per project without changing the template

Very important feature yes.

**Pull request merged**
