### PR TITLE
Custom field 'List' type

### PR DESCRIPTION
**Pull request by luisfontes19**
- Add 'List' type to custom field types... 
- Capitalize custom field types -> "Text", "Input", "List"
- Create tab for custom fields in audit view

image
image

### CODE REVIEW

**Comment by luisfontes19** [comment]
Hey @yeln4ts do you plan to merge or reject the open PR's? To know if its worth to keep fixing the conflicts.

**Comment by noraj** [comment]
@luisfontes19 This feature looks cool

**Comment by yeln4ts** [comment]
Sorry for the late answer. As you've seen I'm going through some changes for now. The goal is to have lots of custom fields but I just want to make sure that the actual model is working good before

**Comment by luisfontes19** [comment]
Implemented in new versions... closing this

**Pull request closed without merging**
